### ISSUE TITLE
Linux系统

### ISSUE THREAD

**Issue by Billyyanyz** [thunlp/OOP-THU#1]
作业里的makefile要求Linux下编译通过，未来各种作业是不是最好在linux环境下去完成，而不是windows？现在装双系统还来得及吗QAQ

**Comment by yylidiw** [comment]
装双系统肯定来得及，但是linux和win差距挺大的，可能需要一个过渡的阶段。课件里的makefile其实也可以在win下进行，效果也是等价的。而且觉得现阶段win和linux对于大多数人的区别可能没那么明显。。。如果在环境变量里加入各种路径的话。。。

**Comment by yylidiw** [comment]
> 作业里的makefile要求Linux下编译通过，未来各种作业是不是最好在linux环境下去完成，而不是windows？现在装双系统还来得及吗QAQ

装双系统肯定来得及，但是linux和win差距挺大的，可能需要一个过渡的阶段。课件里的makefile其实也可以在win下进行，效果也是等价的。而且觉得现阶段win和linux对于大多数人的区别可能没那么明显。。。如果在环境变量里加入各种路径的话。。。

**Comment by yylidiw** [comment]
> 作业里的makefile要求Linux下编译通过，未来各种作业是不是最好在linux环境下去完成，而不是windows？现在装双系统还来得及吗QAQ

还有就是装双系统可能有一定风险吧。。。做好备份。。。

**Comment by zzy14** [comment]
其实还可以不装双系统，现在windows 10上有一个跑Ubuntu bash的程序，可以提供一个linux环境。具体可以参考这个[网页](https://tutorials.ubuntu.com/tutorial/tutorial-ubuntu-on-windows#0).

**Comment by yylidiw** [comment]
> 其实还可以不装双系统，现在windows 10上有一个跑Ubuntu bash的程序，可以提供一个linux环境。具体可以参考这个[网页](https://tutorials.ubuntu.com/tutorial/tutorial-ubuntu-on-windows#0).

那个我舍友试了一下，好像没有搞出来图形界面。其实如果机子不错的话，也可以考虑装虚拟机？

**Comment by yylidiw** [comment]
好吧，刚被win坑了一波。。。ubuntu还是有必要的。。。。

**Comment by Billyyanyz** [comment]
最后还是选择装了个虚拟机，预计会有一丢丢卡但做OOP作业肯定余裕。
过渡？什么过渡？问就两开花（逃
辛苦辛苦吧（
