### ISSUE TITLE
函数返回类的return对象是否析构

### ISSUE THREAD

**Issue by xieyt2000** [thunlp/OOP-THU#10]
hw2第三题的一段代码
A f1(A b) {
	cout << "------after call------" << endl;
	A f;
	cout << "------before return------" << endl;
	return f;
}
…………………………………………
auto testA = f1(b);
有的编译器析构f，有的不析构，求问是什么原因

**Comment by lllizhenyu** [comment]
我认为不析构的情况应该是编译器进行了返回值优化。
如果在命令行用 
![image](https://user-images.githubusercontent.com/41156182/54471556-f127fc80-47f5-11e9-9b26-54158a29b8aa.png)
禁止编译器返回值优化，你应该可以看到f被析构。
（有错误欢迎指出）

**Comment by xieyt2000** [comment]
> 我认为不析构的情况应该是编译器进行了返回值优化。
> 如果在命令行用 如下编译
> ![image](https://user-images.githubusercontent.com/41156182/54471588-3fd59680-47f6-11e9-8be9-58d8bf4b1e3b.png)
> 
> 禁止编译器返回值优化，然后运行，你应该可以看到f被析构。
> （有错误欢迎指出）

那具体是怎么优化的呢？是让左值直接为return变量的引用吗？这个程序里输出f与testA的地址确实是一样的
