### ISSUE TITLE
【HW1】作业第四题Computer类的name, num, price等数据成员的属性（访问权限）问题

### ISSUE THREAD

**Issue by qky18** [thunlp/OOP-THU#11]
首先要考虑的就是，设置成private好，还是public好？
我觉得从这些数据的意义看应该是private比较合适，因为电脑的型号、库存与价格都是相对确定的，不是轻易允许访问和更改的；然后它又必须允许更改，所以不可以是const；并且是每个对象独有的，写成static没有意义，所以它们就是一些普通的private成员。
我想问的就是，如何通过某个Computer类对象的指针去访问、显示甚至更改这些信息？还是说有更好的实现方式？

**Comment by YeDeming** [comment]
设置成private，根据getPrice()函数，setPrice(int price)函数进行修改，即仅接受修改请求，但在类内部操作进行修改

**Comment by qky18** [comment]
> 设置成private，根据getPrice()函数，setPrice(int price)函数进行修改，即仅接受修改请求，但在类内部操作进行修改

那如果是在cin >> cc的时候通过重载输入流运算符，构建了一个Computer类对象的链表，要怎样通过指针去访问这些对象的private成员呢？还是说有更好的实现方式？

**Comment by YeDeming** [comment]
Computer* a;
a = a->getnext();
a->getPrice()

链表跟输入流的关系是？
