### ISSUE TITLE
[HW2]T2题意是什么

### ISSUE THREAD

**Issue by Billyyanyz** [thunlp/OOP-THU#13]
我有点不太理解这道题怎么样算有错误或风险。把程序跑一遍输出都很正常，如果理解成是这些程序片段有没有问题的话，这些都没有问题。
是不是题目的意思是不考虑Test.h里为了避免错误而加入的优化，只看主程序，并把Test类看做某个一般的类，并调用一般的构造析构函数，然后分析程序是不是会错？
这样的话是不是把程序跑一遍跑出来的结果就不能相信了？

**Comment by lllizhenyu** [comment]
有些代码虽然可以run，并且成功退出。但是其内部是有小错误的。举个例子，空指针。所以题目问的是“有没有错误或者风险”。这个风险就是说虽然当前这个代码没出错，但是针对它的漏洞多写几个操作就会出现错误。
