### ISSUE TITLE
计算图大作业相关问题

### ISSUE THREAD

**Issue by youyl** [thunlp/OOP-THU#14]
1.输入情况会不会出现环，比如a=sin b, b=sin c, c=sin a这样的情况？
2.如果一次输入造成多次Error，比如同时造成了分母为零和占位符未赋值的情况，应该输出所有Error信息还是仅仅输出一个？

**Comment by kepei1106** [comment]
1. 不会
2. 仅输出一个。如果错误有依赖关系，则选择依赖关系最早的错误；如果没有依赖关系，就任意输出一个
