### ISSUE TITLE
第三次作业第三题problem 28的delete问题

### ISSUE THREAD

**Issue by nmrenyi** [thunlp/OOP-THU#16]
我的程序中对rp cp sp 都进行了delete
可是却只能成功释放rp
却不能成功释放sp和cp
将把size强制转化为void*类型后就可以成功释放了…
请问这是为什么啊？？？

**Comment by nmrenyi** [comment]
有没有人来解释一下啊，，手动@助教们

**Comment by zzy14** [comment]
正常的操作应该是没有强制转型就可以达成目标的，你可以展示一些你的关键代码便于我们看看原因。
