### ISSUE TITLE
一个正则表达式匹配问题

### ISSUE THREAD

**Issue by LovEveRv** [thunlp/OOP-THU#17]
正则表达式可以做不定个数的匹配捕获吗？例如，对于字符串：
func(x1,123,456);
若现在括号内参数个数不确定，但是我希望能够捕获若干个(,.*)串，也就是实现类似于(,.*)*的效果。
不过直接写(,.*)*发现并不能实现这一目标……
代码：
```cpp
string s("func(x1,23,456);");
regex e(R"((\w+)\((.*)(,.*)*\);)");
smatch sm;
regex_match(s,sm,e);
for(unsigned i=0;i<sm.size();i++) cout << i << ':' << sm[i] << '\n';
```
实际运行结果：
```
0:func(x1,23,456);
1:func
2:x1,23,456
3:
```
（另外为什么捕获了一个空串能否解释一下呢）
恳请解答，谢谢！

**Comment by LovEveRv** [comment]
抱歉上一条里因为有markdown的问题导致没有表达清楚
就是说我想实现类似(,.\*)\*的效果，但是直接这样写并不可以

**Comment by YeDeming** [comment]
可以匹配的，每个括号内十个分组，第0个是完整匹配，后面是每个分组内自己匹配的结果
比如(\w+)是匹配func, (.*)匹配 x1,23,456
在http://tool.chinaz.com/regex/可以实时测试自己的正则表达式

**Comment by LovEveRv** [comment]
> 可以匹配的，每个括号内是一个分组，第0个是完整匹配，后面是每个分组内自己匹配的结果
> 比如(\w+)是匹配func, (._)匹配 x1,23,456，空匹配(,._)*
> 在http://tool.chinaz.com/regex/ 可以实时测试自己的正则表达式
> 感觉可以要用除去逗号之外所有字符之类的匹配你再想想

就是想要用同一个正则表达式去匹配
func(x1,x2,x3);
func(x1,x2,x3,x4,x5);
两个字符串，都能够正确地捕获，也就是对于第一个字符串，它捕获：
(func)(x1)(x2)(x3)
对于第二个字符串，它捕获：
(func)(x1)(x2)(x3)(x4)(x5)
都存在smatch里（均忽略smatch[0]完整匹配）
能够做到吗？直接在捕获块(,.\*)后面加\*表示捕获若干个好像并不可以，把.改成[^,]也没用
如果能做到可否提供这个正则表达式的写法呢
谢谢！

**Comment by LovEveRv** [comment]
问题解决，虽然感觉有点麻烦
原问题出现在：捕获组后面加*是可行的，但是它只会捕获最后一个捕获组
比如用"(abc)+d"去匹配"abcabcabcd"，只会捕获一个abc
可以用regex_search完成这个任务（但是感觉太过麻烦了可能不是很实用）
贴最终代码：
```cpp
    string s("func( x1,23,456, asdlf, 13ldsf_, you);");
    regex e(R"((\w+)\((.*)\);)");
    smatch sm;
    if(regex_match(s,sm,e))
    {
        cout << sm[1] << '\n';
        s = sm[2].str();
        smatch sm1;
        regex_search(s,sm1,regex(R"( *([^,]+))"));
        cout << sm1[1].str() << '\n';
        s = sm1.suffix();
        while(regex_search(s,sm1,regex(R"( *, *([^,]+))")))
        {
            cout << sm1[1].str() << '\n';
            s = sm1.suffix();
        }
    }
```
运行结果：
```
func
x1
23
456
asdlf
13ldsf_
you
```
