### ISSUE TITLE
数据库大作业相关问题

### ISSUE THREAD

**Issue by yueyang2000** [thunlp/OOP-THU#19]
1. 请问一条sql语句中是否可能有关键词大小写混用的情况？变量名是否区分大小写？
2. 请问where clause语句中有含括号的复合表达式吗？and和or的优先级又是怎样的？
3. 输入语法错误或不能执行的错误语句是否需要报错？测例中是否有这类语句？

**Comment by zzy14** [comment]
1. 关键词是可以大小写混用的，列名也是可以大小写混用的；输出的时候按照第一次出现时的大小写形式；
2. 第一阶段先不考虑表达式存在括号的情况，and的优先级高于or（可以参照标准SQL的标准）；
3. 第一阶段不考虑错误的输入以及报错。
