### ISSUE TITLE
数据库大作业问题

### ISSUE THREAD

**Issue by dongbw18** [thunlp/OOP-THU#20]
1、请问“SHOW DATABASES 列列出现有的数据库以及其包含的所有表名。”这个操作能不能给个包含数据表的数据库的样例啊[Facepalm]样例都是没有数据表的数据库？
2、请问default和Extra是不是第一阶段不做过多考虑？

**Comment by dongbw18** [comment]
以及样例一的“SHOW DATABASES”操作输出是按倒序输出的数据库，我们也需要吗？如果规范了数据表的输出格式后，是否也需要倒序输出？

**Comment by dongbw18** [comment]
还希望有“SHOW TABLES”的样例

**Comment by zzy14** [comment]
1. 关于`SHOW DATABASES`这个指令，应该是列出所有数据库即可，不需要列出表名；
2. 是的，default和Extra在第一阶段不做过多考虑；
3. 输出方式应该是按数据库名字的字母顺序进行输出；

关于样例，我们是使用mysql的输出作为标准，不会刻意去考察一些极端的情况。这里建议你自己安装一个mysql，在里面进行一些简单的探索。

对于样例`table.sql`，我们进行如下修改：
```
CREATE DATABASE OOP;
USE OOP;
CREATE TABLE oop_info(stu_id INT NOT NULL, stu_name CHAR, PRIMARY KEY(stu_id));
CREATE TABLE oop_info_1(stu_id INT NOT NULL, stu_name CHAR, PRIMARY KEY(stu_id));
CREATE TABLE oop_info_2(stu_id INT NOT NULL, stu_name CHAR, PRIMARY KEY(stu_id));
SHOW TABLES;
DROP DATABASE OOP;
```
mysql的执行结果是：
```
Tables_in_OOP
oop_info
oop_info_1
oop_info_2
```
