### ISSUE TITLE
数据库大作业问题

### ISSUE THREAD

**Issue by codihobia** [thunlp/OOP-THU#22]
所给样例中有
Database
information_schema
Oop
edc
ijn
mysql
oOp
performance_schema
qaz
那么information_schema和performance_schema有什么区别，是performance_schema为当前使用的数据库而information_schema不是吗

**Comment by zzy14** [comment]
这个是给的输出有些问题，把一些不相关的数据库也列出来了，网络学堂已经更新了一下。正确的是不包含information_schema和performance_schema这些东西的。
