### ISSUE TITLE
计算图大作业相关问题

### ISSUE THREAD

**Issue by youyl** [thunlp/OOP-THU#28]
1.oj上的第一阶段提交什么时候会开放？
2.对原先代码至多允许多大程度的修改？

**Comment by zzy14** [comment]
1. 第一阶段已经结束了，我猜你的意思是第二阶段的提交？在第二阶段截止前几天我们会打开第二阶段的提交窗口，整体节奏和第一阶段类似；
2. 首先你要保证main.cpp仍然可以过第一阶段的测试，其余的修改只要给出合理的解释就是可以的，没有一个至多的限制。如果一份代码有很多需要修改，我相信你们组也不会选择它继续开发。

**Comment by youyl** [comment]
> 
> 
>     1. 第一阶段已经结束了，我猜你的意思是第二阶段的提交？在第二阶段截止前几天我们会打开第二阶段的提交窗口，整体节奏和第一阶段类似；
> 
>     2. 首先你要保证main.cpp仍然可以过第一阶段的测试，其余的修改只要给出合理的解释就是可以的，没有一个至多的限制。如果一份代码有很多需要修改，我相信你们组也不会选择它继续开发。

1.关于第一个问题，我想问的就是第一阶段的提交，方便检查是否仍然满足第一阶段。
3.我还有一个问题，就是在单次EVAL操作中能否保证只有一个grad操作被涉及到？

**Comment by hzhwcmhf** [comment]
1. 第二阶段测试点会包含第一阶段测试，应该是提交前一到两周
3. 测试保证只有一个grad操作，不出现二阶导。 如果你实现了多个grad和二阶导，可以有额外的加分
