### ISSUE TITLE
计算图大作业问题 关于assert

### ISSUE THREAD

**Issue by pb0316** [thunlp/OOP-THU#30]
1. 请问题目要求中写的“能够在变量小于等于0时这个条件时报错。这项功能使得
你能够用Assert(x)来保证x>=0功能”是否有矛盾？
2. 请问当同一个节点（value < 0) 被第二次assert计算时，是否需要再次输出ERROR: Assertion failed？
感谢！

**Comment by hzhwcmhf** [comment]
保证x>0 题面会修改
只要求输出第一次assert的错误；若因为运算顺序不确定造成的，任意输出一个
