### ISSUE TITLE
【HW1】为什么这一Makefile在自己的Linux上能够运行，而在OJ上是MakeError？

### ISSUE THREAD

**Issue by codihobia** [thunlp/OOP-THU#4]
main:  main.o product.o sum.o
        g++ -o main   main.o product.o sum.o
main.o: main.cpp  functions.h
        g++ -c main.cpp 
product.o:product.cpp functions.h
        g++ -c product.cpp
sum.o:sum.cpp functions.h
        g++ -c sum.cpp
clean:
        -rm -f main main.o product.o sum.o
debug:
        -g++ -DDEBUG -o main main.cpp  product.cpp sum.cpp

**Comment by THUCSTHanxu13** [comment]
main: main.o product.o sum.o
	g++ -o main main.o product.o sum.o
main.o: main.cpp functions.h
	g++ -c main.cpp
product.o:product.cpp functions.h
	g++ -c product.cpp
sum.o:sum.cpp functions.h
	g++ -c sum.cpp
clean:
	rm -f main main.o product.o sum.o
debug:
	g++ -DDEBUG -o main main.cpp product.cpp sum.cpp

**Comment by THUCSTHanxu13** [comment]
使用编辑器提交上面这段makefile代码是可以过的

**Comment by THUCSTHanxu13** [comment]
你那个代码使用网页上编辑器直接提交也是可以通过的

**Comment by THUCSTHanxu13** [comment]
看你提交的版本上面，每个g++和rm前面要加tab键的。。。
