### ISSUE TITLE
oop本学期主要笔记整理

### ISSUE THREAD

**Issue by zhaochenyang20** [thunlp/OOP-THU#47]
大家好，下方的清华云盘链接是我和三位同学一同整理的oop本学期的笔记，从L1绪论直到L8虚函数为五一前整理，共7篇，并在五一进行了重写审查。L9之后的内容为五一后整理，共3篇。
https://cloud.tsinghua.edu.cn/d/ccefd5d38f8645208637/

近期不断更新六次选择题的解析，也在该文件夹内。

在课件的基础上，我们尽力做到了对于大多PPT有全面的解读，同时联系前后课程的内容与课程作业，对于课件中的一些操作也有一定的扩展。如果有部分内容存在错误，敬请联系微信：18015766633

可以复制的代码块如下：
https://www.kdocs.cn/l/cckVHQBYqHTo
L1、L2·绪论与编程环境

https://www.kdocs.cn/l/crWXG24bdHPr
L3·封装与接口

https://www.kdocs.cn/l/coTCBYsG5Ne8
L4·创建与销毁·一

https://www.kdocs.cn/l/clSikmcvwx2T
L5·创建与销毁·二

https://www.kdocs.cn/l/cdRSPkfeGGn3
L6·引用与复制

https://www.kdocs.cn/l/cnwLdu940n5H
L7·组合与继承

https://www.kdocs.cn/l/chcvAifQ6lxu
L8·虚函数

https://www.kdocs.cn/l/cmtYpWYM8yho
l9 多态与模板 

https://www.kdocs.cn/l/cjl5CLaRJhNf
L10 模板与STL初步

https://www.kdocs.cn/l/cgwBOfWZC3Rq
L12 函数对象和智能指针

每一节的目录
L1、L2 绪论与编程环境
一、 绪论 ........................................................................................................................................2
1.1 面向对象程序的可靠性....................................................................................................2
1.2 对象的性质 .......................................................................................................................2
二、 源程序的结构、编译、链接.................................................................................................2
2.1 源程序的结构....................................................................................................................2
2.2 预编译指令 .......................................................................................................................2
2.2.1 定义 ........................................................................................................................2
2.2.2 文件包含.................................................................................................................3
2.2.3 宏替换.....................................................................................................................3
2.2.4 条件编译指令.........................................................................................................5
2.2.5 其他预处理指令.....................................................................................................6
2.3 标识符 ...............................................................................................................................7
2.3.1 定义 ........................................................................................................................7
2.3.2 组成 ........................................................................................................................7
2.3.3 定义规则.................................................................................................................7
2.3.4 命名规范（非强制）.............................................................................................7
2.4 编译与链接 .......................................................................................................................8
2.4.1 过程 ........................................................................................................................8
2.4.2 编译指令.................................................................................................................8
2.4.3 链接 ........................................................................................................................8
2.5 头文件 ...............................................................................................................................8
2.5.1 意义 ........................................................................................................................8
2.5.2 例子 ........................................................................................................................8
2.6 函数的声明与定义............................................................................................................9
2.6.1 概念 ........................................................................................................................9
2.6.2 变量的声明与定义.................................................................................................9
2.6.3 extern 关键字...........................................................................................................9
2.6.4 结论 ........................................................................................................................9

L3 封装与接口
一、 函数重载 ................................................................................................................................2
1.1 定义与意义 .......................................................................................................................2
1.2 区别方法 ...........................................................................................................................2
1.3 自动类型转换....................................................................................................................2
1.3.1 定义与性质.............................................................................................................2
1.3.2 优先匹配调用.........................................................................................................2
二、 参数缺省值 ............................................................................................................................3
2.1 定义 ...................................................................................................................................3
2.2 语法 ...................................................................................................................................4
2.3 缺省值保护 .......................................................................................................................4
三、 auto 关键字与 decltype ..........................................................................................................5
3.1 作用与意义 .......................................................................................................................5
3.1.1 自动确定变量的类型..............................................................................................5
3.1.2 追踪返回类型的函数.............................................................................................5
3.1.3 auto 的进一步阐述..................................................................................................6
3.2 auto 其他性质.....................................................................................................................6
3.3 decltype...............................................................................................................................6
3.4 auto 的优势.........................................................................................................................7
5.5 auto 字符例题.....................................................................................................................8
四、封装与内联函数.......................................................................................................................9
4.1 private 与 overload 的先后.................................................................................................9
4.2 内联函数 .........................................................................................................................10
4.2.1 定义与意义...........................................................................................................10
4.2.2 内联函数和宏定义的区别...................................................................................10
4.2.3 内联函数的注意事项...........................................................................................11

创建与销毁·一
创建与销毁·一 ..........................................................................................................................................3
1.1.4 初始化列表和构造函数体的基本区别..........................................................................................3
1.2 委派构造函数实例.............................................................................................................................3
3.2 返回静态局部对象的引用.................................................................................................................3
一、 构造函数与析构函数......................................................................................................................3
1.0 面向对象程序的可靠性 ............................................................................................................3
1.1 构造函数 ....................................................................................................................................3
1.1.1 意义.................................................................................................................................3
1.1.2 语法.................................................................................................................................3
1.1.3 初始化列表.....................................................................................................................4
1.1.4 初始化列表和构造函数体的基本区别.........................................................................4
1.1.5 初始化列表的初始顺序.................................................................................................4
1.2 委派构造函数 ............................................................................................................................5
1.2.1 定义.................................................................................................................................5
1.2.2 意义.................................................................................................................................5
1.2.3 实例.................................................................................................................................5
1.3 就地初始化 .................................................................................................................................6
1.4 默认构造函数 ............................................................................................................................7
1.4.1 定义.................................................................................................................................7
1.4.2 语法.................................................................................................................................7
1.4.3 编译器的额外操作.........................................................................................................7
1.4.4 隐式定义的默认构造函数.............................................................................................7
1.4.5 显式声明默认构造函数.................................................................................................9
1.4.6 显式删除危险构造函数.................................................................................................9
1.5 对象数组的初始化（在 main 中） ........................................................................................10
1.6 析构函数 ..................................................................................................................................10
1.6.1 概述...............................................................................................................................10
1.6.2 语法...............................................................................................................................11
1.6.3 析构顺序.......................................................................................................................11
1.6.4 默认析构函数...............................................................................................................11
二、 对象的析构与构造........................................................................................................................12
2.1 局部对象的构造与析构 ..........................................................................................................12
2.1.1 定义...............................................................................................................................12
2.2.2 全局变量的局限性.......................................................................................................12
三、 引用................................................................................................................................................13
3.1 定义与语法 ..............................................................................................................................13
3.2 结合函数使用 ..........................................................................................................................13
3.3 引用的其他特点 ......................................................................................................................16
四、 运算符重载....................................................................................................................................17
4.1 意义 ..........................................................................................................................................17
4.2 语法 ..........................................................................................................................................17
4.3 具体的重载实例 ......................................................................................................................18
4.3.1 可重载类型...................................................................................................................18
4.3.2 前后缀重载...................................................................................................................19
4.3.3 函数运算符()重载........................................................................................................23
4.3.4 数组下标重载...............................................................................................................24
4.3.5 只能成员函数型重载的运算符...................................................................................26
4.3.6 流运算符重载...............................................................................................................26

创建与销毁·二
一、 变量与静态变量......................................................................................................................2
1.1 四类变量的区别.................................................................................................................2
1.2 静态变量.............................................................................................................................4
1.2.1 定义..........................................................................................................................4
1.2.2 初始化......................................................................................................................4
1.2.3 静态局部变量..........................................................................................................4
1.2.4 静态全局变量..........................................................................................................4
1.2.5 全局变量与局部变量..............................................................................................4
1.2.6 内部可链接与外部可链接......................................................................................4
1.3 Static 数据成员（类变量）................................................................................................5
1.3.0 声明、定义..............................................................................................................5
1.3.1 静态数据成员定义与基本性质..............................................................................6
1.3.2 例子..........................................................................................................................6
1.4 Static 成员函数....................................................................................................................7
1.4.1 定义与基本性质......................................................................................................7
二、 常量数据成员与函数..............................................................................................................7
2.1 常量......................................................................................................................................7
2.1.1 常量的定义..............................................................................................................7
2.1.2 常量的性质..............................................................................................................7
2.2 常量数据成员......................................................................................................................7
2.2.1 常量数据成员的定义..............................................................................................7
2.3 常量成员函数......................................................................................................................8
2.3.1 常量成员函数的定义..............................................................................................8
2.3.2 意义..........................................................................................................................8
2.3.3 写法..........................................................................................................................8
2.4 常量对象.............................................................................................................................8
2.5 常量静态变量.....................................................................................................................8
2.5.1 常量静态变量的意义..............................................................................................8
2.5.2 定义方法..................................................................................................................8
2.5.3 访问权限..................................................................................................................9
2.6 常量静态函数不存在.........................................................................................................9
2.7 重载匹配性.........................................................................................................................9
三、 构造与析构..............................................................................................................................9
3.1 常量对象的析构和构造......................................................................................................9
3.2 静态对象的构造与析构...................................................................................................10
3.3 类静态对象构造与析构...................................................................................................10
3.4 参数对象构造与析构.......................................................................................................11
3.4.1 传递形参................................................................................................................11
3.4.2 传递引用与指针....................................................................................................11
3.4.3 类成员含有指针....................................................................................................12
3.4.4 传入引用的优点....................................................................................................12
四、 对象的 new 和 delete ............................................................................................................12
4.1 概述...................................................................................................................................12
4.2 图示...................................................................................................................................12
4.3 匹配性...............................................................................................................................13
4.3.1 搭配使用................................................................................................................13
4.3.2 搭配不当................................................................................................................13
4.4.3 例子........................................................................................................................13
五、 友元........................................................................................................................................14
5.1 定义与基本性质...............................................................................................................14
5.2 跨类友元...........................................................................................................................14
5.2.1 定义........................................................................................................................14
5.2.2 区域无关性............................................................................................................15
5.2.3 不冲突性................................................................................................................15
5.3 友元类...............................................................................................................................15
5.4 友元的注意事项...............................................................................................................15
5.4.1 非对称性................................................................................................................15
5.4.2 非传递性................................................................................................................15
5.4.3 不可继承................................................................................................................15
5.4.4 不可定义................................................................................................................15

引用与复制
一、 常量引用..................................................................................................................................3
1.1 常量引用的意义.................................................................................................................3
二、 拷贝构造函数..........................................................................................................................3
2.1 定义与语法规则..................................................................................................................3
2.2 调用时机..............................................................................................................................4
2.3 隐式拷贝构造函数.............................................................................................................4
2.4 执行顺序.............................................................................................................................4
2.4.1 基本的执行顺序......................................................................................................5
2.4.2 例子..........................................................................................................................5
2.5 拷贝构造函数的缺陷.........................................................................................................6
2.6 解决方法.............................................................................................................................7
三、 移动构造函数..........................................................................................................................7
3.1 右值与右值引用.................................................................................................................7
3.2 移动构造函数.....................................................................................................................9
3.3 移动语句...........................................................................................................................14
3.4 两类构造函数的调用时机...............................................................................................16
3.4.1 判断依据................................................................................................................16
3.4.2 拷贝构造函数的常见调用时机............................................................................16
3.4.3 移动构造函数的常见调用时机............................................................................16
四、 拷贝与移动赋值运算符........................................................................................................17
4.1 拷贝赋值运算符定义与意义...........................................................................................17
4.2 移动赋值运算符作用与意义...........................................................................................18
4.3 调用时机...........................................................................................................................18
4.4 自动合成的函数与运算符...............................................................................................18
五、 返回值优化............................................................................................................................19
5.1 优化条件............................................................................................................................19
5.2 优化意义............................................................................................................................19
5.3 优化实例............................................................................................................................19
5.4 返回值构造.......................................................................................................................19
六、 delete 与检测.........................................................................................................................20
6.1 Delete 的意义 ....................................................................................................................20
6.2 Delete 的检测 ....................................................................................................................20
6.3 赋值的检测.......................................................................................................................20
七、 move 与类型转换..................................................................................................................21
该部分为第三次作业第二题的解析，建议结合阅读..................................................21
7.1 move 的意义......................................................................................................................21
7.2 例子...................................................................................................................................21
7.3 进一步讨论.......................................................................................................................21
八、 置空性讨论............................................................................................................................22
8.0 析构置空...........................................................................................................................22
8.1 移动置空...........................................................................................................................22
8.2 赋值置空............................................................................................................................23
九、 类型转换................................................................................................................................23
9.1 意义...................................................................................................................................24
9.2 语法...................................................................................................................................24
9.3 例子...................................................................................................................................25
9.4 禁止自动类型转换...........................................................................................................28
9.5 四类强制类型转换...........................................................................................................29

虚函数
虚函数 ..............................................................................................................................................2
readme ..............................................................................................................................................2
一、向上类型转换 ..........................................................................................................................2
1.1 定义 ...................................................................................................................................2
1.2 不允许非 public 继承的向上转换....................................................................................2
1.3 例子 ...................................................................................................................................3
二、对象切片 ..................................................................................................................................3
2.1 定义 ...................................................................................................................................3
2.2 例子 ...................................................................................................................................4
2.3 对象切片的理解................................................................................................................6
2.4 进一步讨论 .......................................................................................................................8
三、虚函数 ....................................................................................................................................11
3.1 函数调用绑定..................................................................................................................11
3.2 虚函数定义 .....................................................................................................................12
3.3 虚函数表 .........................................................................................................................13
3.3.1 概述 ......................................................................................................................13
3.3.2 类的虚表...............................................................................................................13
3.3.3 虚表指针...............................................................................................................14
3.3.4 动态绑定...............................................................................................................15
3.3.5 动态绑定的条件...................................................................................................18
3.3.6 虚指针大小...........................................................................................................18
3.3.7 总结 ......................................................................................................................19
3.4 虚函数与构造、析构......................................................................................................19
3.4.1 虚函数与构造函数...............................................................................................19
3.4.2 虚函数与析构函数...............................................................................................21
3.5 overload, override, redefining...........................................................................................22
3.6 override 关键字 ................................................................................................................25
3.7 final 关键字......................................................................................................................25

组合与继承
一、 组合 ........................................................................................................................................2
1.1 定义 ...................................................................................................................................2
1.2 两种实现方式....................................................................................................................2
1.2.1 共有成员.................................................................................................................2
1.2.2 私有成员.................................................................................................................2
1.2.3 public 接口访问 private 数据..................................................................................2
1.3 构造与析构 .......................................................................................................................5
1.3.1 子对象参数构造.....................................................................................................5
1.3.2 子对象默认构造.....................................................................................................5
1.3.3 构造次序.................................................................................................................5
1.3.4 析构次序.................................................................................................................5
1.3.5 例子 ........................................................................................................................5
二、 继承 ........................................................................................................................................9
2.1 定义 ...................................................................................................................................9
2.3 无法继承 ...........................................................................................................................9
2.4 构造与析构 .....................................................................................................................10
2.5 两类继承方式的选择......................................................................................................13
2.6 成员访问权限..................................................................................................................13
2.7 组合与继承的联系..........................................................................................................17
三、 重写隐藏与重载...................................................................................................................18
3.1 定义 .................................................................................................................................18
3.2 using 一并启用.................................................................................................................20
3.3 using 关键字作用总结.....................................................................................................21
3.3.1 继承基类构造函数、恢复被屏蔽的基类成员函数 ...........................................21
3.3.2 指示命名空间 using namespace std;....................................................................21
3.3.3 将另一个命名空间的成员引入当前命名空间....................................................21
3.3.4 定义类型别名，如：using a = int;......................................................................21
四、 多重继承 ..............................................................................................................................22
4.1 定义、意义与潜在风险..................................................................................................22
例二、 同名成员操作...........................................................................................................24
多态与模板
一、抽象类与纯虚函数............................................................................................................................1
1.1 定义 ............................................................................................................................................1
1.2 抽象类继承 ................................................................................................................................2
1.3 纯虚析构函数 ............................................................................................................................2
1.4 纯虚析构函数和其他纯虚函数的区别 ....................................................................................3
二、 向下类型转换..................................................................................................................................4
2.1 定义 ............................................................................................................................................4
2.2 转换方式 ....................................................................................................................................5
2.2.1 安全向下类型转换.........................................................................................................5
2.2.2 快速向下类型转换.........................................................................................................5
2.2.3 总结.................................................................................................................................7
三、 抽象类与纯虚函数........................................................................................................................11
3.1 多重继承 ..................................................................................................................................11
3.2 例子 ..........................................................................................................................................12
四、 多态 Polymorphism .......................................................................................................................12
4.1 定义 ..........................................................................................................................................12
4.2 优势 ..........................................................................................................................................13
五、 函数模板与类模板........................................................................................................................14
5.1 意义与定义 ..............................................................................................................................14
5.2 实例化与自动推导 ..................................................................................................................15
5.3 模板原理 ..................................................................................................................................18
六、 类模板............................................................................................................................................18
6.1 定义 ..........................................................................................................................................18
6.2 模板参数 ..................................................................................................................................19
6.3 模板与多态 ..............................................................................................................................21

**Comment by zhaochenyang20** [comment]
L1、L2 绪论与编程环境
一、 绪论 ........................................................................................................................................2
1.1 面向对象程序的可靠性....................................................................................................2
1.2 对象的性质 .......................................................................................................................2
二、 源程序的结构、编译、链接.................................................................................................2
2.1 源程序的结构....................................................................................................................2
2.2 预编译指令 .......................................................................................................................2
2.2.1 定义 ........................................................................................................................2
2.2.2 文件包含.................................................................................................................3
2.2.3 宏替换.....................................................................................................................3
2.2.4 条件编译指令.........................................................................................................5
2.2.5 其他预处理指令.....................................................................................................6
2.3 标识符 ...............................................................................................................................7
2.3.1 定义 ........................................................................................................................7
2.3.2 组成 ........................................................................................................................7
2.3.3 定义规则.................................................................................................................7
2.3.4 命名规范（非强制）.............................................................................................7
2.4 编译与链接 .......................................................................................................................8
2.4.1 过程 ........................................................................................................................8
2.4.2 编译指令.................................................................................................................8
2.4.3 链接 ........................................................................................................................8
2.5 头文件 ...............................................................................................................................8
2.5.1 意义 ........................................................................................................................8
2.5.2 例子 ........................................................................................................................8
2.6 函数的声明与定义............................................................................................................9
2.6.1 概念 ........................................................................................................................9
2.6.2 变量的声明与定义.................................................................................................9
2.6.3 extern 关键字...........................................................................................................9
2.6.4 结论 ........................................................................................................................9

**Comment by zhaochenyang20** [comment]
L3 封装与接口
一、 函数重载 ................................................................................................................................2
1.1 定义与意义 .......................................................................................................................2
1.2 区别方法 ...........................................................................................................................2
1.3 自动类型转换....................................................................................................................2
1.3.1 定义与性质.............................................................................................................2
1.3.2 优先匹配调用.........................................................................................................2
二、 参数缺省值 ............................................................................................................................3
2.1 定义 ...................................................................................................................................3
2.2 语法 ...................................................................................................................................4
2.3 缺省值保护 .......................................................................................................................4
三、 auto 关键字与 decltype ..........................................................................................................5
3.1 作用与意义 .......................................................................................................................5
3.1.1 自动确定变量的类型..............................................................................................5
3.1.2 追踪返回类型的函数.............................................................................................5
3.1.3 auto 的进一步阐述..................................................................................................6
3.2 auto 其他性质.....................................................................................................................6
3.3 decltype...............................................................................................................................6
3.4 auto 的优势.........................................................................................................................7
5.5 auto 字符例题.....................................................................................................................8
四、封装与内联函数.......................................................................................................................9
4.1 private 与 overload 的先后.................................................................................................9
4.2 内联函数 .........................................................................................................................10
4.2.1 定义与意义...........................................................................................................10
4.2.2 内联函数和宏定义的区别...................................................................................10
4.2.3 内联函数的注意事项...........................................................................................11

**Comment by zhaochenyang20** [comment]
创建与销毁·一
创建与销毁·一 ..........................................................................................................................................3
1.1.4 初始化列表和构造函数体的基本区别..........................................................................................3
1.2 委派构造函数实例.............................................................................................................................3
3.2 返回静态局部对象的引用.................................................................................................................3
一、 构造函数与析构函数......................................................................................................................3
1.0 面向对象程序的可靠性 ............................................................................................................3
1.1 构造函数 ....................................................................................................................................3
1.1.1 意义.................................................................................................................................3
1.1.2 语法.................................................................................................................................3
1.1.3 初始化列表.....................................................................................................................4
1.1.4 初始化列表和构造函数体的基本区别.........................................................................4
1.1.5 初始化列表的初始顺序.................................................................................................4
1.2 委派构造函数 ............................................................................................................................5
1.2.1 定义.................................................................................................................................5
1.2.2 意义.................................................................................................................................5
1.2.3 实例.................................................................................................................................5
1.3 就地初始化 .................................................................................................................................6
1.4 默认构造函数 ............................................................................................................................7
1.4.1 定义.................................................................................................................................7
1.4.2 语法.................................................................................................................................7
1.4.3 编译器的额外操作.........................................................................................................7
1.4.4 隐式定义的默认构造函数.............................................................................................7
1.4.5 显式声明默认构造函数.................................................................................................9
1.4.6 显式删除危险构造函数.................................................................................................9
1.5 对象数组的初始化（在 main 中） ........................................................................................10
1.6 析构函数 ..................................................................................................................................10
1.6.1 概述...............................................................................................................................10
1.6.2 语法...............................................................................................................................11
1.6.3 析构顺序.......................................................................................................................11
1.6.4 默认析构函数...............................................................................................................11
二、 对象的析构与构造........................................................................................................................12
2.1 局部对象的构造与析构 ..........................................................................................................12
2.1.1 定义...............................................................................................................................12
2.2.2 全局变量的局限性.......................................................................................................12
三、 引用................................................................................................................................................13
3.1 定义与语法 ..............................................................................................................................13
3.2 结合函数使用 ..........................................................................................................................13
3.3 引用的其他特点 ......................................................................................................................16
四、 运算符重载....................................................................................................................................17
4.1 意义 ..........................................................................................................................................17
4.2 语法 ..........................................................................................................................................17
4.3 具体的重载实例 ......................................................................................................................18
4.3.1 可重载类型...................................................................................................................18
4.3.2 前后缀重载...................................................................................................................19
4.3.3 函数运算符()重载........................................................................................................23
4.3.4 数组下标重载...............................................................................................................24
4.3.5 只能成员函数型重载的运算符...................................................................................26
4.3.6 流运算符重载...............................................................................................................26

**Comment by zhaochenyang20** [comment]
创建与销毁·二
一、 变量与静态变量......................................................................................................................2
1.1 四类变量的区别.................................................................................................................2
1.2 静态变量.............................................................................................................................4
1.2.1 定义..........................................................................................................................4
1.2.2 初始化......................................................................................................................4
1.2.3 静态局部变量..........................................................................................................4
1.2.4 静态全局变量..........................................................................................................4
1.2.5 全局变量与局部变量..............................................................................................4
1.2.6 内部可链接与外部可链接......................................................................................4
1.3 Static 数据成员（类变量）................................................................................................5
1.3.0 声明、定义..............................................................................................................5
1.3.1 静态数据成员定义与基本性质..............................................................................6
1.3.2 例子..........................................................................................................................6
1.4 Static 成员函数....................................................................................................................7
1.4.1 定义与基本性质......................................................................................................7
二、 常量数据成员与函数..............................................................................................................7
2.1 常量......................................................................................................................................7
2.1.1 常量的定义..............................................................................................................7
2.1.2 常量的性质..............................................................................................................7
2.2 常量数据成员......................................................................................................................7
2.2.1 常量数据成员的定义..............................................................................................7
2.3 常量成员函数......................................................................................................................8
2.3.1 常量成员函数的定义..............................................................................................8
2.3.2 意义..........................................................................................................................8
2.3.3 写法..........................................................................................................................8
2.4 常量对象.............................................................................................................................8
2.5 常量静态变量.....................................................................................................................8
2.5.1 常量静态变量的意义..............................................................................................8
2.5.2 定义方法..................................................................................................................8
2.5.3 访问权限..................................................................................................................9
2.6 常量静态函数不存在.........................................................................................................9
2.7 重载匹配性.........................................................................................................................9
三、 构造与析构..............................................................................................................................9
3.1 常量对象的析构和构造......................................................................................................9
3.2 静态对象的构造与析构...................................................................................................10
3.3 类静态对象构造与析构...................................................................................................10
3.4 参数对象构造与析构.......................................................................................................11
3.4.1 传递形参................................................................................................................11
3.4.2 传递引用与指针....................................................................................................11
3.4.3 类成员含有指针....................................................................................................12
3.4.4 传入引用的优点....................................................................................................12
四、 对象的 new 和 delete ............................................................................................................12
4.1 概述...................................................................................................................................12
4.2 图示...................................................................................................................................12
4.3 匹配性...............................................................................................................................13
4.3.1 搭配使用................................................................................................................13
4.3.2 搭配不当................................................................................................................13
4.4.3 例子........................................................................................................................13
五、 友元........................................................................................................................................14
5.1 定义与基本性质...............................................................................................................14
5.2 跨类友元...........................................................................................................................14
5.2.1 定义........................................................................................................................14
5.2.2 区域无关性............................................................................................................15
5.2.3 不冲突性................................................................................................................15
5.3 友元类...............................................................................................................................15
5.4 友元的注意事项...............................................................................................................15
5.4.1 非对称性................................................................................................................15
5.4.2 非传递性................................................................................................................15
5.4.3 不可继承................................................................................................................15
5.4.4 不可定义................................................................................................................15

**Comment by zhaochenyang20** [comment]
引用与复制
一、 常量引用..................................................................................................................................3
1.1 常量引用的意义.................................................................................................................3
二、 拷贝构造函数..........................................................................................................................3
2.1 定义与语法规则..................................................................................................................3
2.2 调用时机..............................................................................................................................4
2.3 隐式拷贝构造函数.............................................................................................................4
2.4 执行顺序.............................................................................................................................4
2.4.1 基本的执行顺序......................................................................................................5
2.4.2 例子..........................................................................................................................5
2.5 拷贝构造函数的缺陷.........................................................................................................6
2.6 解决方法.............................................................................................................................7
三、 移动构造函数..........................................................................................................................7
3.1 右值与右值引用.................................................................................................................7
3.2 移动构造函数.....................................................................................................................9
3.3 移动语句...........................................................................................................................14
3.4 两类构造函数的调用时机...............................................................................................16
3.4.1 判断依据................................................................................................................16
3.4.2 拷贝构造函数的常见调用时机............................................................................16
3.4.3 移动构造函数的常见调用时机............................................................................16
四、 拷贝与移动赋值运算符........................................................................................................17
4.1 拷贝赋值运算符定义与意义...........................................................................................17
4.2 移动赋值运算符作用与意义...........................................................................................18
4.3 调用时机...........................................................................................................................18
4.4 自动合成的函数与运算符...............................................................................................18
五、 返回值优化............................................................................................................................19
5.1 优化条件............................................................................................................................19
5.2 优化意义............................................................................................................................19
5.3 优化实例............................................................................................................................19
5.4 返回值构造.......................................................................................................................19
六、 delete 与检测.........................................................................................................................20
6.1 Delete 的意义 ....................................................................................................................20
6.2 Delete 的检测 ....................................................................................................................20
6.3 赋值的检测.......................................................................................................................20
七、 move 与类型转换..................................................................................................................21
该部分为第三次作业第二题的解析，建议结合阅读..................................................21
7.1 move 的意义......................................................................................................................21
7.2 例子...................................................................................................................................21
7.3 进一步讨论.......................................................................................................................21
八、 置空性讨论............................................................................................................................22
8.0 析构置空...........................................................................................................................22
8.1 移动置空...........................................................................................................................22
8.2 赋值置空............................................................................................................................23
九、 类型转换................................................................................................................................23
9.1 意义...................................................................................................................................24
9.2 语法...................................................................................................................................24
9.3 例子...................................................................................................................................25
9.4 禁止自动类型转换...........................................................................................................28
9.5 四类强制类型转换...........................................................................................................29

**Comment by zhaochenyang20** [comment]
虚函数
虚函数 ..............................................................................................................................................2
readme ..............................................................................................................................................2
一、向上类型转换 ..........................................................................................................................2
1.1 定义 ...................................................................................................................................2
1.2 不允许非 public 继承的向上转换....................................................................................2
1.3 例子 ...................................................................................................................................3
二、对象切片 ..................................................................................................................................3
2.1 定义 ...................................................................................................................................3
2.2 例子 ...................................................................................................................................4
2.3 对象切片的理解................................................................................................................6
2.4 进一步讨论 .......................................................................................................................8
三、虚函数 ....................................................................................................................................11
3.1 函数调用绑定..................................................................................................................11
3.2 虚函数定义 .....................................................................................................................12
3.3 虚函数表 .........................................................................................................................13
3.3.1 概述 ......................................................................................................................13
3.3.2 类的虚表...............................................................................................................13
3.3.3 虚表指针...............................................................................................................14
3.3.4 动态绑定...............................................................................................................15
3.3.5 动态绑定的条件...................................................................................................18
3.3.6 虚指针大小...........................................................................................................18
3.3.7 总结 ......................................................................................................................19
3.4 虚函数与构造、析构......................................................................................................19
3.4.1 虚函数与构造函数...............................................................................................19
3.4.2 虚函数与析构函数...............................................................................................21
3.5 overload, override, redefining...........................................................................................22
3.6 override 关键字 ................................................................................................................25
3.7 final 关键字......................................................................................................................25

**Comment by zhaochenyang20** [comment]
组合与继承
一、 组合 ........................................................................................................................................2
1.1 定义 ...................................................................................................................................2
1.2 两种实现方式....................................................................................................................2
1.2.1 共有成员.................................................................................................................2
1.2.2 私有成员.................................................................................................................2
1.2.3 public 接口访问 private 数据..................................................................................2
1.3 构造与析构 .......................................................................................................................5
1.3.1 子对象参数构造.....................................................................................................5
1.3.2 子对象默认构造.....................................................................................................5
1.3.3 构造次序.................................................................................................................5
1.3.4 析构次序.................................................................................................................5
1.3.5 例子 ........................................................................................................................5
二、 继承 ........................................................................................................................................9
2.1 定义 ...................................................................................................................................9
2.3 无法继承 ...........................................................................................................................9
2.4 构造与析构 .....................................................................................................................10
2.5 两类继承方式的选择......................................................................................................13
2.6 成员访问权限..................................................................................................................13
2.7 组合与继承的联系..........................................................................................................17
三、 重写隐藏与重载...................................................................................................................18
3.1 定义 .................................................................................................................................18
3.2 using 一并启用.................................................................................................................20
3.3 using 关键字作用总结.....................................................................................................21
3.3.1 继承基类构造函数、恢复被屏蔽的基类成员函数 ...........................................21
3.3.2 指示命名空间 using namespace std;....................................................................21
3.3.3 将另一个命名空间的成员引入当前命名空间....................................................21
3.3.4 定义类型别名，如：using a = int;......................................................................21
四、 多重继承 ..............................................................................................................................22
4.1 定义、意义与潜在风险..................................................................................................22
例二、 同名成员操作...........................................................................................................24

**Comment by zhaochenyang20** [comment]
最近一次更新，重写了L7部分有误的代码

**Comment by zhaochenyang20** [comment]
由于该笔记的讨论在刘老师课堂与黄老师课堂均有进行，在黄老师课堂的讨论较多，相关链接如下：
https://github.com/thu-coai/THUOOP/issues/35
欢迎大家移步

**Comment by zhaochenyang20** [comment]
https://www.kdocs.cn/l/cm9zkqqPviBK
[金山文档] l6·引用与复制.pdf
https://www.kdocs.cn/l/cf36weqxDcYU
[金山文档] l5·创建与销毁·二.pdf
https://www.kdocs.cn/l/cl2hQUqtJ4Ip
[金山文档] l8·虚函数.pdf
https://www.kdocs.cn/l/cuQ4zjs9uvvP
[金山文档] l7·组合与继承.pdf
https://www.kdocs.cn/l/cgI8aqXhSPGA
[金山文档] l4·创建与销毁·一.pdf
https://www.kdocs.cn/l/cdprBet220YL
[金山文档] l1、l2·绪论与编程环境.pdf
https://www.kdocs.cn/l/cnVgamA84QYy
[金山文档] l3·封装与接口.pdf

**Comment by zhaochenyang20** [comment]
如需复制具体的代码，欢迎点击上方金山文档链接

**Comment by luohk19** [comment]
一直很想写一次OOP总结，知识点太多了

**Comment by Btlmd** [comment]
知识点总结到位，i了i了
![](http://img.doutula.com/production/uploads/image/2018/01/26/20180126944080_JHRvSl.jpg)

**Comment by lichenyu20** [comment]
tql

**Comment by zhaochenyang20** [comment]
我们会在近期上传oop选择题的整理，供大家参考
