### ISSUE TITLE
makefile分步编译执行makedebug的问题

### ISSUE THREAD

**Issue by fanglinthu** [thunlp/OOP-THU#5]
在分步编译的makefile写法中，-DDEBUG应该加在编译生成.o文件的指令中，还是加在由.o文件链接生成可执行文件的指令中，抑或二者都需要加？

**Comment by Clide-thu** [comment]
如果我没理解错的话，我觉得是在编译时加

> 在分步编译的makefile写法中，-DDEBUG应该加在编译生成.o文件的指令中，还是加在由.o文件链接生成可执行文件的指令中，抑或二者都需要加？

**Comment by MonsterYi** [comment]
加在编译生成.o文件的指令中
