### ISSUE TITLE
创建和销毁对象时，子函数调用默认构造函数时为什么会多一个销毁过程？

### ISSUE THREAD

**Issue by OldNew777** [thunlp/OOP-THU#6]
#include <iostream>
using namespace std;

class ass{
public:
	char* name;
	ass(){
		cout << "constructing...\n";
	}
	ass(char* name1){
		name = name1;
		ass();
	}
	~ass(){
		cout << "destructing...\n";
	}
};

int main(){
	ass k("boynextdoor");
	cout << k.name << '\n';
	return 0;
}

最后输出为什么是
constructing...
destructing...
boynextdoor
destructing...

**Comment by MonsterYi** [comment]
在ass(char* name1)函数中调用了ass();产生了一个临时量，第二行destructing...是销毁这个临时量输出的

**Comment by qky18** [comment]
> 在ass(char* name1)函数中调用了ass();产生了一个临时量，第二行destructing...是销毁这个临时量输出的

可是为什么这里调用了ass()（默认构造函数）但是没有输出constructing？

**Comment by MonsterYi** [comment]
> > 在ass(char* name1)函数中调用了ass();产生了一个临时量，第二行destructing...是销毁这个临时量输出的
> 
> 可是为什么这里调用了ass()（默认构造函数）但是没有输出constructing？

这个constructing就是调用这个ass()输出的呀

**Comment by qky18** [comment]
> 在ass(char* name1)函数中调用了ass();产生了一个临时量，第二行destructing...是销毁这个临时量输出的
> 
> 可是为什么这里调用了ass()（默认构造函数）但是没有输出constructing？
> 
> 这个constructing就是调用这个ass()输出的呀

啊对！之前看的时候看串了……
