### ISSUE TITLE
类B  中含有另一类A 对象的初始化问题

### ISSUE THREAD

**Issue by Xiaoyu-SZ** [thunlp/OOP-THU#7]
类A定义（想要同时保留两个构造函数）
class A {
	string x ;//*? 
public:
	A(string p){
		x = p ；
	}
	A(){
	}
	~A(){
	}
};

类B定义
class B {
private:
	static A data1;
	string y ;	
	//A data2;
public：
	B(){	
	//A data2(y+"->data2") ;
	}
	~B(){
	}
};

想对B中的 A data2 进行初始化：
如果将第一处注释 A data2 改为 A data2("string") 则出现编译错误。
如果将第一处注释保留，加上第二处注释以初始化，那么将会构建两个A，并析构两次。
那么如何只构建一次并完成初始化呢orz

**Comment by lllizhenyu** [comment]
之前群里应该有讨论过这个问题， A data2("string")编译出错是因为编译器不允许这样初始化。借鉴群友的说法， A data2={ "STRING" }应该可以成功。
