### ISSUE TITLE
如何理解最后一行代码

### ISSUE THREAD

**Issue by Andision** [thunlp/OOP-THU#8]
struct A { double x; };
const A* a;
 
decltype(a->x) y;       // type of y is double (declared type)
decltype((a->x)) z = y; // type of z is const double& (lvalue expression)

为什么加了一层括号后类型改变了

**Comment by lllizhenyu** [comment]
我也不太懂，不过我这里好像看不出来差别。
![草图](https://user-images.githubusercontent.com/41156182/54401448-b09b8680-4702-11e9-90f9-70f25c798d8f.png)

**Comment by zzy14** [comment]
加括号类型改变这个语法是c++11规定的，更多详细的语法规定可以参考[这个网页](https://en.cppreference.com/w/cpp/language/decltype).

**Comment by MonsterYi** [comment]
如果decltype使用的是一个不加括号的变量，则得到的结果就是该变量的类型；如果给变量加上了一层或多层括号，编译器就会把它当成是一个表达式。变量是一种可以作为赋值语句左值的特殊表达式，所以这样的decltype就会得到引用类型。
decltype((variable))的结果永远是引用，decltype(variable)结果只有当variable本身就是一个引用时才是引用。
另外，如果表达式的内容是解引用操作，如decltype(*p)，则返回的结果也是引用类型。
